package com.example.performance.step2

internal val articleText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Commodo odio aenean sed adipiscing. Mi eget mauris pharetra et ultrices. Ullamcorper malesuada proin libero nunc consequat interdum. Congue eu consequat ac felis donec. Nec sagittis aliquam malesuada bibendum. Pretium aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Nisi porta lorem mollis aliquam ut porttitor leo. Et malesuada fames ac turpis egestas maecenas. Eu consequat ac felis donec et odio. Lectus quam id leo in. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Augue eget arcu dictum varius. Elementum nisi quis eleifend quam adipiscing vitae. Tellus cras adipiscing enim eu turpis egestas. Sed libero enim sed faucibus.\n" +
        "\n" +
        "Arcu vitae elementum curabitur vitae nunc sed. Risus feugiat in ante metus dictum at tempor commodo. Mi ipsum faucibus vitae aliquet nec ullamcorper. Purus sit amet volutpat consequat mauris nunc. Velit egestas dui id ornare arcu odio ut sem nulla. Quis varius quam quisque id diam. Eu lobortis elementum nibh tellus molestie. Semper viverra nam libero justo laoreet sit. Bibendum at varius vel pharetra. Purus non enim praesent elementum facilisis leo vel. Egestas egestas fringilla phasellus faucibus. Massa tempor nec feugiat nisl pretium fusce. Nunc lobortis mattis aliquam faucibus purus in massa tempor. Risus viverra adipiscing at in tellus. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Hac habitasse platea dictumst vestibulum rhoncus est. Dui faucibus in ornare quam viverra orci. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis.\n" +
        "\n" +
        "Eu consequat ac felis donec et odio. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Euismod quis viverra nibh cras pulvinar mattis nunc. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. Congue eu consequat ac felis donec et odio. Dignissim sodales ut eu sem. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Viverra vitae congue eu consequat ac felis donec. Mauris a diam maecenas sed. Venenatis lectus magna fringilla urna porttitor. Morbi tristique senectus et netus. Elementum curabitur vitae nunc sed velit dignissim. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Proin libero nunc consequat interdum varius. Mattis enim ut tellus elementum sagittis vitae et leo duis. Lacus viverra vitae congue eu consequat ac felis donec et. Leo vel orci porta non pulvinar neque laoreet. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Aenean et tortor at risus viverra adipiscing at in. Neque gravida in fermentum et sollicitudin ac orci.\n" +
        "\n" +
        "Blandit turpis cursus in hac habitasse. Proin sed libero enim sed faucibus turpis. Consequat interdum varius sit amet mattis vulputate. Id donec ultrices tincidunt arcu non sodales. Tellus at urna condimentum mattis pellentesque id nibh. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Iaculis eu non diam phasellus. Scelerisque viverra mauris in aliquam sem fringilla. Orci eu lobortis elementum nibh tellus. Nunc faucibus a pellentesque sit amet porttitor eget dolor morbi. Non odio euismod lacinia at quis risus. Vitae tempus quam pellentesque nec. Pharetra et ultrices neque ornare aenean. Cursus in hac habitasse platea dictumst quisque sagittis purus. Eget arcu dictum varius duis.\n" +
        "\n" +
        "Nullam non nisi est sit amet. Nunc scelerisque viverra mauris in aliquam. Scelerisque viverra mauris in aliquam. Commodo elit at imperdiet dui accumsan sit amet nulla. Adipiscing elit duis tristique sollicitudin nibh sit amet. Tortor at auctor urna nunc id. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Aliquet nec ullamcorper sit amet. Bibendum enim facilisis gravida neque convallis a cras semper. Velit scelerisque in dictum non consectetur a. Iaculis nunc sed augue lacus. Gravida neque convallis a cras semper. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Lectus sit amet est placerat in egestas erat imperdiet sed. Quis commodo odio aenean sed adipiscing diam donec.\n" +
        "\n" +
        "Mi bibendum neque egestas congue quisque egestas. Integer vitae justo eget magna. Ultrices dui sapien eget mi proin sed libero enim. Habitasse platea dictumst quisque sagittis purus sit amet. Ut venenatis tellus in metus vulputate eu scelerisque. Praesent semper feugiat nibh sed pulvinar proin gravida. Adipiscing elit ut aliquam purus. Erat velit scelerisque in dictum non consectetur a. Egestas congue quisque egestas diam in arcu cursus euismod quis. In dictum non consectetur a erat nam at. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl.\n" +
        "\n" +
        "Ac odio tempor orci dapibus ultrices in. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Magna fringilla urna porttitor rhoncus dolor purus non enim. Pellentesque elit eget gravida cum. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Eros in cursus turpis massa. Placerat vestibulum lectus mauris ultrices eros in. Ut etiam sit amet nisl purus in. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Donec et odio pellentesque diam volutpat commodo sed egestas egestas. Eget nullam non nisi est sit amet facilisis magna.\n" +
        "\n" +
        "Elit eget gravida cum sociis. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem. In nulla posuere sollicitudin aliquam ultrices. Enim facilisis gravida neque convallis a cras semper auctor neque. Semper auctor neque vitae tempus. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Massa tincidunt nunc pulvinar sapien et ligula. In pellentesque massa placerat duis ultricies lacus sed turpis. Turpis egestas integer eget aliquet nibh praesent. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Leo vel orci porta non pulvinar neque laoreet. Ac odio tempor orci dapibus ultrices. Tellus id interdum velit laoreet id. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Erat velit scelerisque in dictum non consectetur a. Interdum consectetur libero id faucibus nisl tincidunt. Ut lectus arcu bibendum at varius.\n" +
        "\n" +
        "Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Nunc sed velit dignissim sodales ut eu sem. Turpis egestas maecenas pharetra convallis posuere morbi leo. Turpis egestas pretium aenean pharetra magna. Dolor sit amet consectetur adipiscing elit ut aliquam. Vivamus arcu felis bibendum ut tristique. Venenatis urna cursus eget nunc scelerisque viverra. Vulputate odio ut enim blandit volutpat. Diam vel quam elementum pulvinar etiam non quam lacus. Est lorem ipsum dolor sit amet. Id nibh tortor id aliquet.\n" +
        "\n" +
        "Vitae congue eu consequat ac felis donec et odio pellentesque. Felis eget velit aliquet sagittis. Facilisis volutpat est velit egestas dui id ornare arcu. Augue eget arcu dictum varius duis at consectetur lorem. Amet luctus venenatis lectus magna fringilla urna. Arcu odio ut sem nulla pharetra. Ultricies integer quis auctor elit sed. Faucibus scelerisque eleifend donec pretium vulputate sapien. Tempus iaculis urna id volutpat. Etiam tempor orci eu lobortis elementum. Vitae et leo duis ut diam quam nulla.\n" +
        "\n" +
        "Vulputate ut pharetra sit amet aliquam id diam. Cursus risus at ultrices mi tempus imperdiet nulla. Laoreet sit amet cursus sit amet. Purus in mollis nunc sed id semper risus in hendrerit. Neque egestas congue quisque egestas diam. Leo in vitae turpis massa. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Massa sapien faucibus et molestie ac. Sem viverra aliquet eget sit amet tellus. Volutpat odio facilisis mauris sit amet. Nulla pellentesque dignissim enim sit amet venenatis urna cursus. Tellus molestie nunc non blandit massa enim. Vitae semper quis lectus nulla at volutpat diam ut. At quis risus sed vulputate odio ut. Nullam eget felis eget nunc.\n" +
        "\n" +
        "Ut tortor pretium viverra suspendisse potenti nullam ac. Arcu dui vivamus arcu felis bibendum ut. Purus in mollis nunc sed id semper risus. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Neque gravida in fermentum et. Sed vulputate mi sit amet mauris commodo quis. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Dui ut ornare lectus sit amet. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Quis blandit turpis cursus in hac habitasse. Felis eget nunc lobortis mattis aliquam faucibus purus. Facilisis gravida neque convallis a cras semper auctor. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Neque vitae tempus quam pellentesque nec nam aliquam sem et.\n" +
        "\n" +
        "Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Nascetur ridiculus mus mauris vitae ultricies leo integer. Sed felis eget velit aliquet sagittis id consectetur. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Ipsum suspendisse ultrices gravida dictum fusce. At urna condimentum mattis pellentesque id nibh tortor. Lacus vel facilisis volutpat est velit egestas dui. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Consectetur a erat nam at lectus. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Porttitor lacus luctus accumsan tortor posuere ac ut consequat.\n" +
        "\n" +
        "Bibendum enim facilisis gravida neque convallis a cras semper auctor. Sapien pellentesque habitant morbi tristique senectus et. Interdum posuere lorem ipsum dolor. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Ac felis donec et odio pellentesque diam. Ultricies mi eget mauris pharetra et ultrices neque ornare. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Consequat semper viverra nam libero justo laoreet sit amet cursus. Ac turpis egestas sed tempus urna et pharetra. Ullamcorper a lacus vestibulum sed arcu non. Vestibulum sed arcu non odio euismod lacinia at. Aenean pharetra magna ac placerat vestibulum lectus. At tellus at urna condimentum mattis pellentesque id nibh. Cursus euismod quis viverra nibh cras pulvinar. Aliquam purus sit amet luctus. Vitae auctor eu augue ut lectus arcu bibendum at varius. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Egestas diam in arcu cursus euismod quis viverra.\n" +
        "\n" +
        "Posuere sollicitudin aliquam ultrices sagittis orci. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Quis enim lobortis scelerisque fermentum dui faucibus in. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Sapien eget mi proin sed libero. Ac turpis egestas integer eget. Purus non enim praesent elementum facilisis leo. Sit amet nisl purus in mollis nunc. Amet est placerat in egestas erat imperdiet sed. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Eu mi bibendum neque egestas congue. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Malesuada fames ac turpis egestas. Lobortis scelerisque fermentum dui faucibus in ornare quam. Nibh cras pulvinar mattis nunc. Commodo elit at imperdiet dui accumsan sit amet nulla. Enim sit amet venenatis urna cursus. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Sed enim ut sem viverra aliquet eget. Elit ullamcorper dignissim cras tincidunt.\n" +
        "\n" +
        "Tincidunt dui ut ornare lectus sit amet est placerat in. Pellentesque dignissim enim sit amet venenatis urna. Scelerisque felis imperdiet proin fermentum leo. Risus viverra adipiscing at in tellus integer feugiat. Pretium lectus quam id leo in vitae. Dui ut ornare lectus sit. Commodo ullamcorper a lacus vestibulum. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Urna porttitor rhoncus dolor purus non enim praesent.\n" +
        "\n" +
        "Ac tortor dignissim convallis aenean et tortor at risus viverra. Nunc mi ipsum faucibus vitae aliquet. Ac turpis egestas maecenas pharetra convallis. Turpis nunc eget lorem dolor sed viverra. Ornare lectus sit amet est. Aliquet sagittis id consectetur purus ut faucibus. In nisl nisi scelerisque eu ultrices vitae auctor. Mauris augue neque gravida in. Tellus molestie nunc non blandit massa. Massa sed elementum tempus egestas sed sed risus pretium. At varius vel pharetra vel turpis nunc eget lorem. Massa tincidunt dui ut ornare lectus sit. Sit amet mattis vulputate enim. Nunc aliquet bibendum enim facilisis gravida neque convallis. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum.\n" +
        "\n" +
        "Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. A diam sollicitudin tempor id. Volutpat lacus laoreet non curabitur. Purus in massa tempor nec feugiat nisl pretium fusce. Tempus quam pellentesque nec nam aliquam. Ultrices vitae auctor eu augue ut lectus arcu. Eleifend mi in nulla posuere sollicitudin aliquam. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien.\n" +
        "\n" +
        "Scelerisque fermentum dui faucibus in. Facilisis sed odio morbi quis commodo odio. Quam id leo in vitae turpis massa. Varius duis at consectetur lorem donec massa sapien faucibus. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Tincidunt eget nullam non nisi est sit amet facilisis magna. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Fames ac turpis egestas maecenas pharetra. Senectus et netus et malesuada. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Scelerisque fermentum dui faucibus in ornare quam.\n" +
        "\n" +
        "Libero enim sed faucibus turpis in eu mi bibendum neque. Auctor eu augue ut lectus arcu bibendum at varius vel. Risus pretium quam vulputate dignissim. Viverra suspendisse potenti nullam ac tortor vitae purus. Eu ultrices vitae auctor eu augue ut lectus. Morbi non arcu risus quis varius quam quisque. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Risus ultricies tristique nulla aliquet enim. Dolor magna eget est lorem. Fermentum leo vel orci porta non. Mauris vitae ultricies leo integer malesuada. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Luctus venenatis lectus magna fringilla urna porttitor rhoncus. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Aliquam vestibulum morbi blandit cursus. Sed risus ultricies tristique nulla aliquet. Dignissim diam quis enim lobortis."